apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-nginx
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30081


